spring:
  application:
    name: backend-assignment
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
        jdbc:
          time_zone: UTC
      show-sql: true

invoice-service.url: "http://localhost:8000"